
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '124396BCB134EDD04A9CA14108CC27C7'
    
_lr_action_items = {'HEADINGS':([0,],[3,]),'$end':([1,4,5,9,10,],[0,-1,-6,-5,-4,]),'BAR':([2,5,7,8,10,],[7,7,7,-7,-4,]),'NL':([3,6,7,11,],[8,10,-3,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'spreadsheet':([0,],[1,]),'headings':([0,],[2,]),'blank_lines':([2,5,],[4,9,]),'blank_line':([2,5,],[5,5,]),'blanks':([2,5,7,],[6,6,11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> spreadsheet","S'",1,None,None,None),
  ('spreadsheet -> headings blank_lines','spreadsheet',2,'p_spreadsheet','08.py',77),
  ('blanks -> BAR blanks','blanks',2,'p_blanks','08.py',82),
  ('blanks -> BAR','blanks',1,'p_blanks','08.py',83),
  ('blank_line -> blanks NL','blank_line',2,'p_blank_line','08.py',88),
  ('blank_lines -> blank_line blank_lines','blank_lines',2,'p_blank_lines','08.py',92),
  ('blank_lines -> blank_line','blank_lines',1,'p_blank_lines','08.py',93),
  ('headings -> HEADINGS NL','headings',2,'p_headings','08.py',98),
  ('line -> LINE','line',1,'p_line','08.py',104),
  ('number -> LINE BAR','number',2,'p_number','08.py',109),
  ('option1 -> blanks line blanks','option1',3,'p_option1','08.py',113),
  ('option1 -> blanks','option1',1,'p_option1','08.py',114),
  ('options -> line blanks NL','options',3,'p_options','08.py',119),
  ('part1 -> question type option1 NL','part1',4,'p_part1','08.py',124),
  ('part2 -> blanks options NL','part2',3,'p_part2','08.py',129),
  ('part3 -> blanks options NL','part3',3,'p_part3','08.py',135),
  ('part3 -> NL','part3',1,'p_part3','08.py',136),
  ('question -> BAR BAR questionTitle','question',3,'p_question','08.py',141),
  ('question -> number section questionTitle','question',3,'p_question','08.py',142),
  ('questionBlocks -> questionBlock questionBlocks','questionBlocks',2,'p_questionBlocks','08.py',149),
  ('questionBlocks -> questionBlock','questionBlocks',1,'p_questionBlocks','08.py',150),
  ('questionBlock -> blank_line','questionBlock',1,'p_questionBlock','08.py',155),
  ('questionTitle -> line BAR','questionTitle',2,'p_questionTitle','08.py',160),
  ('section -> LINE BAR','section',2,'p_section','08.py',165),
  ('type -> line BAR','type',2,'p_type','08.py',169),
]
